import {StyleSheet} from 'react-native';
import {getFontSize, getHeight, getWidth} from '../../../../utils/ResponsiveFun';

export const styles = StyleSheet.create({
  contaner: {
    flex: 1,
  },
  mview: {
    height: getHeight(12),
    width: getWidth(88),
    justifyContent: 'space-between',

    alignItems: 'center',

    flexDirection: 'row',
    alignSelf: 'center',
  },
  main: {
    flex: 1,
    alignItems: 'center',
    alignSelf: 'center',
    
    width: getWidth(90),
  },
  headerDivider: {
    height: 1,
    backgroundColor: '#182d4a26',
    borderRadius: 10,
    width: '93%',
    marginTop: 15,

    alignSelf: 'center',
  },
  skip: {color: '#EB5757', fontWeight: '400', fontSize: 12},
  linearGradient: {
    alignSelf: 'center',
    width: getWidth(88),
    position: 'absolute',
    bottom: getHeight(5),
    height: getHeight(6),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
  },
  heding:{
    fontSize: 12,
    lineHeight: 15,

    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
  },
  maindiscription:{
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'Ubuntu-Regular',
    lineHeight: 14,
    color: '#182d4a',
    marginTop: getHeight(1),
  },
  youtube:{
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: getHeight(2.3),
  },
  videoguideline:{
    fontSize: 14,
    lineHeight: 17,
    fontFamily: 'Ubuntu-Bold',
    marginLeft: getWidth(2),
    color: '#182d4a',
  },
  record:{
    fontSize: 12,
    fontFamily: 'Ubuntu-Bold',
    lineHeight: 15,
    color: '#182d4a',
    marginTop: getHeight(2.3),
  },
  Discrip:{
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'Ubuntu-Regular',
    fontWeight: '400',
    color: '#182d4a',
    marginTop: getHeight(1),
    width: getWidth(90),
  },
  setss:{
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    lineHeight: 15,
    color: '#182d4a',
  },
  reps:{
    marginLeft: getWidth(10),
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    lineHeight: 15,
    color: '#182d4a',
  },
  labs:{
    marginLeft: getWidth(25),
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    lineHeight: 15,
    color: '#182d4a',
  },
  plusminus:{
    marginTop: getHeight(5),
    alignItems: 'center',
    flexDirection: 'row',
  },
  minusView:{
    height: 40,
    width: 40,
    borderRadius: 20,
    borderColor: '#182d4a20',
    justifyContent: 'center',
    borderWidth: 1,
    alignItems: 'center',
  },
  minus:{
    color: '#182d4a50',
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'Ubuntu-Bold',
    lineHeight: 27,
  },
  sets:{
    color: '#182d4a',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Ubuntu-Bold',
    lineHeight: 15,
    width: getWidth(10),
    marginLeft: getWidth(4),
    alignSelf: 'center',
  },
  plusview:{
    height: 40,
    width: 40,
    borderRadius: 20,
    borderColor: '#182d4a',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  plus:{
    color: '#182d4a',
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'Ubuntu-Bold',
    lineHeight: 27,
  },
  WorkOutDays:{
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    lineHeight: 14,
    marginTop: 5,
    marginBottom: getHeight(1),
    fontSize: 12,
  },
  image: {
    width: getWidth(35),
    marginLeft: getWidth(4.5),
    height: getHeight(12),
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#182d4a15',
  },
  requView:{
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: getHeight(1.5),
    width: getWidth(90),
    alignItems: 'center',
  },
  indexnumbring:{
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    lineHeight: 15,
    color: '#182d4a',
  },
  requirements:{
    borderRadius: 15,

    width: getWidth(32),
    height: getHeight(5),
    textAlign:'center',
    backgroundColor: 'white',},
  tCheck:{
    borderRadius: 15,
  
    width: getWidth(32),
    textAlign:'center',
    height: getHeight(5),
    backgroundColor: 'white',
  },
  check:{
    height: 26,
    backgroundColor: '#182d4a',
    width: 26,
    borderRadius: 13,
    marginRight: getWidth(1),
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadFile:{
    height: getHeight(5.5),
    width: getWidth(93),
    backgroundColor: '#182d4a10',
    borderRadius: 15,
    alignSelf: 'center',
  },
  Camera:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: getWidth(88),
    height: getHeight(5),
    alignItems: 'center',
    alignSelf: 'center',
  },
  attach:{color: '#182d4a', fontFamily: 'Ubuntu-Regular'},
  missMark:{
    color: '#EB5757',
    fontSize: 14,
    fontFamily: 'Ubuntu-Bold',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    padding: 15,
    marginLeft: getWidth(30),
  },
  icon1: {
    position:'absolute',
    top:0,
    right:0,
   },
   text: {color: '#7D5098', alignSelf: 'center', fontSize: 12},
  Description:{
    color: '#182d4a',
    fontFamily: 'Ubuntu-Regular',
    lineHeight: 14,
    textAlign:'left',
    width:getWidth(91),
    marginBottom: getHeight(1.5),
    fontSize: 12,
  },
  comments:{
    flexDirection:'row',
    alignItems:'center',
    marginLeft:getWidth(5),
    marginTop:getHeight(2)
      },
  commentsBox:{
    width:getWidth(93),
    
    borderColor:'#182d4a26',
    borderWidth:0.7,
    
    marginTop:getHeight(1),
    backgroundColor:'white',
    borderRadius:15,
    alignSelf:'center',
  },
  mainview:{ 
    height:getHeight(30),
    width:'100%',
    backgroundColor:'white',
    borderRadius:15,
    alignItems:'center',
  },
  mainview1:{ 
    height:getHeight(70),
    width:'100%',
    backgroundColor:'white',
    borderRadius:15,
    alignItems:'center',
  },
  secView1:{
    width:getWidth(99),
    justifyContent:'space-around',
    alignContent:'center',
    alignItems:'center',
    flexDirection:'row'
  },
    secView:{
      width:getWidth(99),
      justifyContent:'space-around',
      alignContent:'center',
      alignItems:'center',
      flexDirection:'row'
    },
      taskview:{
        color:'#182d4a',
        fontSize:18,
        fontFamily:'Ubuntu-Bold'
      },
        videostyle:{
          width: getWidth(85),
          marginTop:getHeight(3),
          borderRadius: 10,
         
        },
        atteched:{
          color:'#182d4a',
          alignSelf:'center',
          marginRight:getWidth(36),
          fontSize:14,
          fontFamily:'Ubuntu-Bold'
        },
        neview:{width: getWidth(85),
          backgroundColor:'#182d4a20',
          height: getHeight(6),
          marginTop:getHeight(1),
          justifyContent:'center',
          flexDirection:'row',
          alignItems: 'flex-start',
          borderRadius: 15,
        },

  footer:{height:getHeight(5),flexDirection:'row',alignItems:'flex-end',alignSelf:'flex-end',margin:10},
});
