import {StyleSheet} from 'react-native';
import {getFontSize, getHeight, getWidth} from '../../../../utils/ResponsiveFun';

export const styles = StyleSheet.create({
  contaner: {
    flex: 1,
  },
  headerDivider: {
    height: 1,
    backgroundColor: '#182d4a26',
    borderRadius: 10,
    width: '93%',
    marginTop: 15,
    alignSelf: 'center',
  },
  main: {
    alignSelf: 'center',
    width: getWidth(100),
    paddingTop: getHeight(2),
    flex: 1,
    paddingHorizontal: getWidth(5),
  },
  openBox: {
    alignSelf: 'center',
    width: getWidth(91),
    backgroundColor: 'white',
    alignItems: 'center',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 1,

    elevation: 1.5,
  },
  list: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: getWidth(5),
    width: getWidth(91),
    backgroundColor: 'white',
    borderRadius: 15,
    margin: 7,
    height: getHeight(6),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 1,
    elevation: 1.5,
  },
  list2: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: getWidth(5),
    width: getWidth(91),
    backgroundColor: 'white',
    borderRadius: 15,
    margin: 7,
    height: getHeight(6),
  },
  planView: {
    width: getWidth(90),
    marginTop: getHeight(1.5),
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: getWidth(5),
    height: getHeight(9),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 0.9,
    elevation: 0.5,
  },
  planText: {
    color: '#182d4a',
    fontSize: 12,
    left: 3,
    lineHeight: 15,
    fontFamily: 'Ubuntu-Bold',
    marginTop: getHeight(1.5),
  },
  planPrice: {
    color: '#182d4a',
    fontSize: 24,
    lineHeight: 27,
    marginTop:getHeight(2),
    fontFamily: 'Ubuntu-Bold',
  },
  planMonth: {
    color: '#182d4a40',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 15,
    fontFamily: 'Ubuntu-Regular',
  },
  heading: {
    color: '#182d4a',
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'Ubuntu-Bold',
  },
  mview: {
    marginTop: getHeight(2.5),
    marginBottom: getHeight(1.5),
    width: getWidth(80),
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    alignSelf: 'center',
  },
  skip: {
    color: '#EB5757',
    fontSize: 14,
    fontFamily: 'Ubuntu-Bold',
    lineHeight: 17,
  },
  linearGradient: {
    alignSelf: 'center',
    width: getWidth(30),
    height: getHeight(5.5),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
  },
});
