export const fonts = {
  Re: "RussoOne-Regular",
  Me: "RussoOne-Medium",
  Bo: "RussoOne-Bold",
  URe: "Ubuntu-Regular",
  UBo: "Ubuntu-Bold",
  UMe: "Ubuntu-Medium",
  UBIt: "Ubuntu-BoldItalic",
  UMIt: "Ubuntu-MediumItalic",
  WB: "WorkSans-Bold",
  WL: "WorkSans-Light",
  WM: "WorkSans-Medium",
  WR: "WorkSan-Regular",
  WSB: "WorkSan-SemiBolf",
};
