import { Platform, StyleSheet } from "react-native";
import {
  getHeight,
  getFontSize,
  getWidth,
} from "../../../../utils/ResponsiveFun";
import { colors } from "../../../constants/colors";
import { fonts } from "../../../constants/fonts";

export const styles = StyleSheet.create({
  buttonMark: {
    width: getWidth(90),
    backgroundColor: colors.buttonColor,
    height: getHeight(6),
    borderRadius: 5,
    alignSelf: "center",
    marginBottom: getHeight(3),
    justifyContent: "center",
    alignItems: "center",
  },
  rest2: {
    fontFamily: fonts.UBo,
    color: colors.white,
    fontSize: getFontSize(2),
    marginRight: getWidth(2),
  },
  tickCon: {
    height: getHeight(4),
    width: getHeight(4),
    borderRadius: 30,
    backgroundColor: colors.graytext5,
    marginLeft: getWidth(2),
    justifyContent: "center",
    alignItems: "center",
  },
  submitCon: {
    height: getHeight(3),
    width: getHeight(3),
    borderRadius: 22.5,
    justifyContent: "center",
    alignItems: "center",
  },
  parameterCon: {
    color: colors.blackOp,
    fontSize: getFontSize(2),
    marginTop: getFontSize(0.5),
    fontFamily: fonts.URe,
    textAlign: "center"

  },
  lbsCol: {
    width: getWidth(17),
    justifyContent: "center",
    alignItems: "center",
  },
  setName: {
    color: colors.blackOp,
    fontWeight: "900",
    fontSize: getFontSize(2.2),
    fontFamily: fonts.URe,
    textAlign: "center"
  },
  setCon: {
    flexDirection: "column",
    width: getWidth(19),
    marginRight: getFontSize(2),
    marginLeft: getFontSize(1),

  },
  setParameter: {
    width: getWidth(5),
    marginLeft: getFontSize(2),
    alignItems: 'center',
    justifyContent: "soace-between",
    flexDirection: "row",
  },
  setView: {
    backgroundColor: colors.whiteOp20,
    height: getHeight(6),
    width: getWidth(14),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: getFontSize(1),
  },
  setText: {
    fontSize: getFontSize(1.7),
    position: 'absolute', alignSelf: 'center', top: getHeight(4),
    textAlign: "center",
    marginRight: getWidth(0),
    color: colors.black2,
    fontFamily: fonts.URe,
  },
  setContainer: {
    backgroundColor: colors.blackDarkOp,
    height: getHeight(10),
    width: getWidth(15),
    alignItems: "center",
    justifyContent: "center",
    // borderRadius: getFontSize(0.75),
    borderBottomLeftRadius: 30,
    borderTopLeftRadius: 30
  },
  setParams: {
    width: getWidth(14),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: getFontSize(1),
    backgroundColor: colors.orange,
  },
  exerciseParamas: {
    //flexDirection: "row",
    //alignItems: "center",
    //justifyContent: "space-between",
    width: getWidth(90),

    //marginTop: getFontSize(1),
  },
  lbs: {
    fontSize: getFontSize(2),
    color: colors.gray8,
    fontFamily: fonts.URe,
    // marginTop: getHeight(0.5),
    textAlign: "center",
    fontWeight: "600",
    //right:getFontSize(1.5)
  },
  dashes: {
    fontSize: getFontSize(2),
    color: colors.graytext4,
    fontFamily: fonts.URe,
  },
  horizental: {
    width: getWidth(0.5),
    height: getHeight(3),
    backgroundColor: colors.graytext5,
  },
  reps: {
    fontSize: 10,
    color: colors.graytext4,
    fontFamily: fonts.URe,
    marginTop: getHeight(0.5),
    textAlign: "center",
  },
  numbr: {
    fontSize: getFontSize(2),
    fontFamily: fonts.URe,
    color: colors.darktext,
    // marginLeft: getWidth(-3),
  },
  count: {
    fontSize: getFontSize(2.2),
    color: colors.white,
    fontFamily: fonts.URe,
    marginRight: getWidth(2),
  },
  btnhor: {
    height: getHeight(3.5),
    width: getWidth(18),
    backgroundColor: colors.greenlight,
    borderRadius: 5,
  },
  spabet: {
    flexDirection: "row",
    alignItems: "center",
    height: getHeight(3),
    marginTop: getHeight(2.5),
  },
  markas: {
    color: colors.white,
    fontSize: getFontSize(2.2),
    fontFamily: fonts.UBo,
  },
  heading: {
    width: getWidth(100),
    flexDirection: "row",
    alignItems: "center",
    height: getHeight(8),
    backgroundColor: "#000",
    justifyContent: "space-between",
  },
  videobtn: {
    width: getWidth(25),
    //height: getHeight(4),
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: colors.primary,
    //position: "absolute",
    //bottom: getHeight(2.5),
    //left: getWidth(3),
  },
  overlayContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  flatchest: {
    fontSize: getFontSize(3),
    color: colors.white,
    fontFamily: fonts.UBo,
    position: "absolute",
    bottom: getHeight(7),
    left: getWidth(3),
  },
  flatchest1: {
    fontSize: getFontSize(2.5),
    color: colors.white,
    fontFamily: fonts.UBo,
    position: "absolute",
    bottom: getHeight(4),
    left: getWidth(3),
  },
  videotext: { fontSize: 10, fontFamily: fonts.UBo, color: colors.white },
  start: {
    color: colors.white,
    fontSize: getFontSize(1.7),
    fontFamily: fonts.UBo,
    marginLeft: getWidth(1),
  },
  togle: {
    backgroundColor: colors.whiteOp20,
    height: getHeight(5),
    borderRadius: 5,
    width: getWidth(20),
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    // marginLeft: getWidth(10),
  },
  angel: {
    height: getHeight(8),
    flexDirection: "row",
    alignItems: "center",
    width: getWidth(100),
  },
  text: {
    marginHorizontal: 4,
    fontSize: Platform.OS === "ios" ? getFontSize(5.2) : getFontSize(4),
    fontFamily: fonts.Re,
    color: colors.black,
    marginLeft: getWidth(2),
  },
  header: {
    //flex:1,
    flexDirection: "column",
    alignItems: "center",
    marginRight: 38,
  },
  repsCon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: getHeight(8),
    marginTop: getHeight(3),
    backgroundColor: colors.secondary1,
    width: getWidth(90),
    // paddingLeft:getFontSize(1),
    paddingRight: getFontSize(1),
    borderRadius: getFontSize(1),
  },
  headerTime: {
    //flex:1,
    flexDirection: "row",
    // marginTop: 5,
  },
  betww: {
    width: getWidth(78),
    height: getHeight(3.5),
    borderRadius: 5,
    backgroundColor: colors.secondary,
    flexDirection: "row",
    alignItems: "center",
  },
  whiteCon: {
    width: getWidth(65),
    height: getHeight(6),
    // borderRadius: 5,
    // borderWidth: 1,
    borderColor: colors.graytext5,
    // backgroundColor: 'rgba(79,79,79,0.1)',
    flexDirection: "row",
    paddingLeft: getFontSize(3),
  },
  heading: {
    height: getHeight(3.5),
    backgroundColor: colors.secondary,
    width: getWidth(95),
    alignSelf: "center",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  headingtext: {
    fontSize: getFontSize(1.9),
    color: colors.graytext4,
    fontFamily: fonts.UBo,
  },
  imgb: { height: getHeight(30), width: getWidth(100) },
  spacebet: {
    flexDirection: "row",
    alignItems: "center",
    height: getHeight(3),
    marginTop: getHeight(2.5),
    marginLeft: getFontSize(2),
  },
  rest: {
    fontFamily: fonts.UBo,
    color: colors.white,
    fontSize: getFontSize(2),
    // marginRight: getWidth(2),
    width: getWidth(32),
    height: getHeight(10),
  },
  btng: {
    width: getFontSize(22),
    height: getHeight(3.5),
    borderRadius: 5,
    backgroundColor: colors.secondary,
    flexDirection: "row",
    alignItems: "center",
  },
  playerbtn: {
    height: getHeight(7),
    width: getHeight(7),
    borderRadius: getHeight(7) / 2,
    backgroundColor: "rgba(255,255,255,0.4)",
    //opacity: 0.5,
    justifyContent: "center",
    alignItems: "center",
  },
  rowDirection: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    right: getFontSize(2),
  },
  parameterCtn: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  notes: {
    fontFamily: "Ubuntu",
    color: colors.primary,
    fontSize: getFontSize(1.7),
    width: getWidth(75),
    borderRadius: 5,
    backgroundColor: colors.white,
    paddingLeft: getFontSize(3),
    paddingTop: getFontSize(1),
    marginLeft: getWidth(7.5),
    marginTop: getHeight(2),
    height: getHeight(10),
    paddingBottom: Platform.OS === "ios" ? getFontSize(0) : getFontSize(7),
    fontWeight: "normal",
  },
  notesText: {
    color: "white",
    marginTop: getFontSize(2),
    left: getFontSize(2),
    fontSize: getFontSize(2),
    fontFamily: fonts.URe,
    marginRight: getWidth(2),
  },
  notesStyle: {
    marginTop: getFontSize(2),
    backgroundColor: colors.secondary1,
    width: getWidth(90),
    justifyContent: "center",
    alignItems: "center",
    paddingTop: getFontSize(1.5),
    paddingBottom: getFontSize(1.5),
    borderRadius: getFontSize(0.5),
    marginBottom: getFontSize(1)
  },
  additionalSet: {
    marginTop: getFontSize(2),
    backgroundColor: colors.secondary1,
    width: getWidth(90),
    height: getHeight(6),
    justifyContent: "center",
    alignItems: "center",
    // paddingTop:getFontSize(1.5),
    // paddingBottom:getFontSize(1.5),
    borderRadius: getFontSize(0.5),
    borderWidth: 1,
    borderColor: colors.blackOp,
    borderStyle: "dashed",
  },
});
