import {StyleSheet} from 'react-native';
import {
  getFontSize,
  getHeight,
  getWidth,
} from '../../../../utils/ResponsiveFun';

export const styles = StyleSheet.create({
  contaner: {
    flex: 1,
  },
  headerDivider: {
    height: 1,
    backgroundColor: '#182d4a26',
    borderRadius: 10,
    width: '93%',
    marginTop: 15,

    alignSelf: 'center',
  },
  workoutsNumbring: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
  },
  WorkOutDays: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    lineHeight: 14,
    marginLeft: 7,
    marginTop: 5,
    marginBottom: getHeight(1),
    fontSize: 12,
  },
  Description: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Regular',
    lineHeight: 14,
    marginLeft: 7,
    textAlign: 'left',
    width: getWidth(91),
    marginBottom: getHeight(1.5),
    fontSize: 12,
  },
  comments: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: getWidth(1.5),
  },
  tabBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: getHeight(2),
    marginBottom: getHeight(2),
    height: getHeight(7),
    justifyContent: 'space-around',
    backgroundColor: '#CDDAEC',

    alignSelf: 'center',
    borderRadius: 15,
    width: getWidth(90),
  },
  tabItem: {
    borderRadius: 10,
    backgroundColor: '#182d4a',
    alignItems: 'center',
    justifyContent: 'center',
    height: getHeight(4),
    width: getWidth(33),
    marginLeft: getWidth(5),
    marginRight: getWidth(5),
    alignSelf: 'center',
  },
  unselect: {
    alignItems: 'center',
    alignSelf: 'center',
    flex: 1,
    marginLeft: getWidth(5),
    marginRight: getWidth(5),
    justifyContent: 'center',
    height: getHeight(5),
  },
  selectedTabText: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 14,
    lineHeight: 17,
  },
  TabTex: {
    fontFamily: 'Ubuntu-Bold',
    fontSize: 14,
    lineHeight: 17,
    color: '#182d4a',
  },
  listItem: {
    alignSelf: 'center',
    width: getWidth(91),
    backgroundColor: 'white',
    borderRadius: 15,
    paddingHorizontal: getWidth(5),
    height: getHeight(6),
    flexDirection: 'row',
    margin: 7,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  circle: {
    height: 26,
    backgroundColor: '#182d4a',
    width: 26,
    borderRadius: 13,
    marginRight: getWidth(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    lineHeight: 15,
  },
  alignView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  main: {
    alignSelf: 'center',
    paddingTop: getHeight(2),
  },
  commentsBox: {
    width: getWidth(93),
    borderColor: '#182d4a26',
    borderWidth: 0.7,
    marginTop: getHeight(1),
    backgroundColor: 'white',
    borderRadius: 15,
    alignSelf: 'center',
  },
  check: {
    height: 26,
    backgroundColor: '#182d4a15',
    width: 26,
    borderRadius: 13,
    marginRight: getWidth(5),
    justifyContent: 'center',
    alignItems: 'center',
  },

  check1: {
    height: 26,
    backgroundColor: '#182d4a',
    width: 26,
    borderRadius: 13,
    marginRight: getWidth(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  img: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    flex: 1,
    marginTop: getHeight(15),
  },
  CommentsText: {
    color: '#182d4a',
    marginLeft: 10,
    marginTop: 5,
    width: getWidth(87),
    textAlign: 'left',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 12,
    marginBottom: 10,
  },
  cooldown:{
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 10,
  },
  prof:{
    justifyContent: 'flex-start',
    flexDirection: 'row',
    marginLeft: 10,
    marginTop: 10,
  },
  youText: {fontFamily: 'Ubuntu-Bold', color: '#182d4a', fontSize: 12},
  justifyView: {flexDirection: 'row', justifyContent: 'space-between'},
  camera: {flexDirection: 'row', margin: 10},
  attechText: {color: '#182d4a', fontFamily: 'Ubuntu-Regular'},
  send: {
    height: getHeight(6),
    width: getWidth(12),
    backgroundColor: '#7D5098',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    margin: 5,
  },
  expand: {
    color: '#182d4a',
    fontSize: 10,
    fontFamily: 'Ubuntu-Bold',
    fontSize: 10,
  },
  profImage: {width: 40, height: 40, borderRadius: 25},
  coachComments: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    marginLeft: 10,
    marginTop: 10,
  },
  commentImage: {
    margin: 10,
    height: getHeight(11),
    width: getWidth(27),
    borderRadius: 15,
  },
  commentText: {
    color: '#182d4a',
    marginLeft: 10,
    marginTop: 5,
    width: getWidth(87),
    textAlign: 'left',
    fontFamily: 'Ubuntu-Regular',
    fontSize: 12,
  },
  DateTime: {fontFamily: 'Ubuntu-SemiBold', color: '#182d4a', fontSize: 10},
  traner: {fontFamily: 'Ubuntu-SemiBold', color: '#182d4a', fontSize: 10},
  profilename: {fontFamily: 'Ubuntu-Bold', color: '#182d4a', fontSize: 12},
  commentsheader: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    marginLeft: 7,
  },
  profileview: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    marginLeft: 10,
    marginTop: 10,
  },
  exer: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    marginLeft: 7,
  },
  backerrow: {alignSelf: 'center', marginRight: getWidth(2)},
  head: {flex: 1, backgroundColor: 'white'},
  listError: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 15,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: getHeight(2),
  },
  img: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    flex: 1,
    marginTop: getHeight(5),
  },
  listError: {
    color: '#182d4a',
    fontFamily: 'Ubuntu-Bold',
    fontSize: 12,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: getHeight(1),
  },
  footer: {
    height: getHeight(5),
    flexDirection: 'row',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    margin: 10,
  },
});
